Banner (incomplete)
material-components/material-components-web pull request #4359
Opened 2019-02-06 09:56 UTC by lyubov-voloshko

HTML and CSS for banner.

Is it OK or, please, point what should be corrected?

2019-03-21 15:16 UTC, lubo commented
Hi, what's the hold-up here?

2019-04-11 14:37 UTC, hjhart commented
Hey there! We are hoping to be able to use this component soon. Any updates on when we'll get a review and release?

2020-01-04 15:50 UTC, neotsn commented
If this work is done, can the appropriate people handle the remaining tasks and push it through? The longer it sits, the more stale it gets.

2020-04-30 03:25 UTC, SampsonCrowley commented
Bump

2020-04-30 03:28 UTC, SampsonCrowley requested changes
missing a closing quote in README html structure (line 43)

2020-04-30 03:28 UTC, SampsonCrowley commented on packages/mdc-banner/README.md
> +  <div class="mdc-banner>
missing a closing quote

2020-06-17 17:25 UTC, dotteddice commented
I couldn't find the original branch used for this PR... how do we resolve the merge conflicts?

2022-07-10 03:49 UTC, anlexN commented
can we solve PR?

2025-01-13 20:43 UTC, closed without merging