build: add google-recommended resizeObserver types
material-components/material-components-web pull request #6453
Opened 2020-09-04 01:11 UTC by e111077

2020-09-04 02:36 UTC, asyncLiz requested changes

2020-09-04 02:36 UTC, asyncLiz commented on package.json
> +    "@types/resize-observer-browser": "^0.1.3",
there should be a package-lock.json change as well?

2020-09-08 18:15 UTC, e111077 commented
ping!

2020-09-08 18:29 UTC, asyncLiz approved these changes

2020-09-08 19:07 UTC, merged