Changed `query` to `options` in getting-started.md
material-components/material-components-web pull request #6704
Opened 2020-12-18 01:32 UTC by facorread

Changed `query` to `options` according to https://webpack.js.org/loaders/babel-loader/

2020-12-29 21:23 UTC, asyncLiz requested changes
Thanks for fixing this! Just two adjustments to make to add the `use: { ... }` block for webpack rules that I think we're missing.

Additionally, can you go ahead and sign the CLA so that we can accept this PR?

2020-12-29 21:23 UTC, asyncLiz commented on docs/getting-started.md
>       },
Looks like this section is missing the `use: { ... }` block for webpack rules

```suggestion
     use: {
       loader: 'babel-loader',
       options: {
         presets: ['@babel/preset-env'],
       },
     },
```

2020-12-29 21:23 UTC, asyncLiz commented on docs/getting-started.md
>          },
```suggestion
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
```

2022-07-10 04:04 UTC, anlexN commented
what is CLA? so many duplicated webpack problems. can we solve PR?

2025-01-13 20:43 UTC, closed without merging