[Documentation] Fix require syntax for importing javascript
material-components/material-components-web pull request #6713
Opened 2020-12-24 01:56 UTC by Ishaangandhi

`mdc-foo` is not consistent with other path examples. It let me to believe to require 'switch', for example, I'd use `require('mdc-switch')`. However, what you need is `require('@material/switch'`

2020-12-24 01:57 UTC, Ishaangandhi commented
@googlebot I signed it!

2020-12-28 20:56 UTC, asyncLiz requested changes
Thanks for the PR!

Do you mind also updating the AMD section?

```js
require(['path/to/@material/foo'], mdcFoo => {
  const MDCFoo = mdcFoo.MDCFoo;
  const MDCFooFoundation = mdcFoo.MDCFooFoundation;
});
```

2020-12-28 21:15 UTC, Ishaangandhi commented
@asyncLiz Yes, how about that?

2020-12-29 20:04 UTC, asyncLiz approved these changes
Looks good! Thanks for the fix 🙂

2020-12-29 20:18 UTC, asyncLiz commented
It looks like there may have been a problem importing the PR since we just did a release. Can you [merge the upstream `master` branch into your repository](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork), then merge your updated `master` into your `patch-1` branch?

2020-12-30 00:07 UTC, merged